# Schema for the configuration files of the country_access_filter module.

country_access_filter.settings:
  type: config_object
  label: 'Country Access Filter settings'
  mapping:
    enabled:
      type: boolean
      label: 'Enable functionality'
    countries:
      type: string
      label: 'Allowed countries'
    track_404:
      type: boolean
      label: 'Track 404 requests'
    track_404_threshold:
      type: integer
      label: '404 threshold before banning IP'
    track_404_window:
      type: integer
      label: 'Time window in seconds to count 404s'
